config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  resources :links

  get '*code' => 'links#redirect', as: :short

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :original_url, presence: true

  default_scope -> { order('original_url DESC') }

  before_create :generate_code

  def generate_code
    self.code = SecureRandom.hex[0..3]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find params[:id]
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new params[:link].permit(:original_url)
    #@link.code = SecureRandom.hex[0..6]

    if @link.save
      redirect_to @link
    else
      flash[:alert] = "Link sa nepodarilo uložiť"
      render :new
    end
  end

  def destroy
    @link = Link.find params[:id]
    @link.destroy
    flash[:notice] = "Link bol odstránený."
    redirect_to links_url
  end

  def redirect
    @link = Link.where(code: params[:code]).first
    if @link
      @link.visit_count += 1
      @link.save
      redirect_to @link.original_url
    else
      flash[:alert] = "Neznámy odkaz"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skrat.to</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">

  <div class="row">
    <div class="col-sm-6">
      <h1><%= link_to "Skráť.to", root_path %></h1>
    </div>

    <div class="col-sm-6 text-right" style="margin-top: 20px;">
      <%= link_to "Chcem skrátiť link", new_link_path, class: 'btn btn-success' %>
    </div>
  </div>

  <hr>

  <%= content_tag :p, flash[:alert] if flash[:alert] %>

  <%= yield %>

</div>

</body>
</html>

app/views/links/index.html.erb
<h2>Posledné linky</h2>

<table class="table">
  <thead>
    <tr>
      <th class="col-sm-5">URL</th>
      <th class="col-sm-3">Skrátená URL</th>
      <th class="col-sm-2">Pocet otvoreni</th>
      <th class="col-sm-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.original_url %></td>
        <td><%= link_to short_url(link.code), short_url(link.code) %></td>
        <td><%= link.visit_count %></td>
        <td>
          <%= link_to "Zobraziť", link %>
          <%= link_to "Odstrániť", link, method: :delete, data: { confirm: "Určite?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/new.html.erb
<div class="col-sm-6 col-sm-offset-3">

  <div class="panel panel-default">
    <div class="panel-heading">
      Skrátiť link
    </div>

    <div class="panel-body">

      <%= form_for @link do |f| %>
        <div class="form-group">
          <%= f.label :original_url, "URL adresa" %>
          <%= f.text_field :original_url, class: 'form-control' %>
        </div>

        <%= f.submit "Skrátiť", class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>

</div>

app/views/links/show.html.erb
<h2>Odkaz</h2>

<div class="panel panel-default">
  <div class="panel-body">

    <p class="lead" style="margin: 0;">
      <%= link_to short_url(@link.code), short_url(@link.code) %>
    </p>
  </div>

  <div class="panel-footer">
    Originálna URL:
    <%= link_to @link.original_url %>
  </div>
</div>

<p>
  <%= link_to "Pokračovať na hlavnú stránku", root_path, class: 'btn btn-default' %>
</p>